// AUTO-GENERATED by scripts/generateFontArtifacts.mts — DO NOT EDIT
import { globalFontFace } from '@vanilla-extract/css';

const fontFaces = [
  {
    fontFamily: 'Object Sans',
    fontStyle: 'normal',
    fontWeight: 400,
    fontDisplay: 'swap',
    src: 'url("https://cdn.lafleche.dev/release/fonts/v1/Object+Sans.gen/PPObjectSans-Regular.6e1490d0.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Object+Sans.gen/PPObjectSans-Slanted.6e1490d0.woff2") format("woff2")',
  },
  {
    fontFamily: 'Object Sans',
    fontStyle: 'normal',
    fontWeight: 900,
    fontDisplay: 'swap',
    src: 'url("https://cdn.lafleche.dev/release/fonts/v1/Object+Sans.gen/PPObjectSans-Heavy.6e1490d0.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Object+Sans.gen/PPObjectSans-HeavySlanted.6e1490d0.woff2") format("woff2")',
  },
] as const;

for (const face of fontFaces) {
  const { fontFamily, ...fontFace } = face;
  globalFontFace(fontFamily, fontFace);
}

