// AUTO-GENERATED by scripts/generateFontArtifacts.mts — DO NOT EDIT
import { globalFontFace } from '@vanilla-extract/css';

const fontFaces = [
  {
    fontFamily: 'Fraktion Mono',
    fontStyle: 'italic',
    fontWeight: 400,
    fontDisplay: 'swap',
    src: 'url("https://cdn.lafleche.dev/release/fonts/v1/Fraktion+Mono.gen/PPFraktionMono-RegularItalic.e9233dc1.woff2") format("woff2")',
  },
  {
    fontFamily: 'Fraktion Mono',
    fontStyle: 'normal',
    fontWeight: 400,
    fontDisplay: 'swap',
    src: 'url("https://cdn.lafleche.dev/release/fonts/v1/Fraktion+Mono.gen/PPFraktionMono-Bold.e9233dc1.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Fraktion+Mono.gen/PPFraktionMono-Regular.e9233dc1.woff2") format("woff2")',
  },
  {
    fontFamily: 'Fraktion Sans',
    fontStyle: 'italic',
    fontWeight: 300,
    fontDisplay: 'swap',
    src: 'url("https://cdn.lafleche.dev/release/fonts/v1/Fraktion+Sans.gen/PPFraktionSans-BoldItalic.45f17c3c.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Fraktion+Sans.gen/PPFraktionSans-LightItalic.45f17c3c.woff2") format("woff2")',
  },
  {
    fontFamily: 'Fraktion Sans',
    fontStyle: 'normal',
    fontWeight: 300,
    fontDisplay: 'swap',
    src: 'url("https://cdn.lafleche.dev/release/fonts/v1/Fraktion+Sans.gen/PPFraktionSans-Bold.45f17c3c.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Fraktion+Sans.gen/PPFraktionSans-Light.45f17c3c.woff2") format("woff2")',
  },
  {
    fontFamily: 'Neue Montreal',
    fontStyle: 'italic',
    fontWeight: 100,
    fontDisplay: 'swap',
    src: 'url("https://cdn.lafleche.dev/release/fonts/v1/Neue+Montreal.gen/PPNeueMontreal-Italic.01869a6e.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Neue+Montreal.gen/PPNeueMontreal-SemiBolditalic.01869a6e.woff2") format("woff2")',
  },
  {
    fontFamily: 'Neue Montreal',
    fontStyle: 'normal',
    fontWeight: 100,
    fontDisplay: 'swap',
    src: 'url("https://cdn.lafleche.dev/release/fonts/v1/Neue+Montreal.gen/PPNeueMontreal-Bold.01869a6e.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Neue+Montreal.gen/PPNeueMontreal-Book.01869a6e.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Neue+Montreal.gen/PPNeueMontreal-Medium.01869a6e.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Neue+Montreal.gen/PPNeueMontreal-Thin.01869a6e.woff2") format("woff2")',
  },
  {
    fontFamily: 'Object Sans',
    fontStyle: 'normal',
    fontWeight: 400,
    fontDisplay: 'swap',
    src: 'url("https://cdn.lafleche.dev/release/fonts/v1/Object+Sans.gen/PPObjectSans-Heavy.6e1490d0.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Object+Sans.gen/PPObjectSans-HeavySlanted.6e1490d0.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Object+Sans.gen/PPObjectSans-Regular.6e1490d0.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Object+Sans.gen/PPObjectSans-Slanted.6e1490d0.woff2") format("woff2")',
  },
  {
    fontFamily: 'Pangram Sans',
    fontStyle: 'italic',
    fontWeight: 100,
    fontDisplay: 'swap',
    src: 'url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-CompactThinItalic.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-ExtraboldItalic.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-NarrowExtraboldItalic.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-NarrowSemiboldItalic.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-SlimSemiboldItalic.d6aeafc5.woff2") format("woff2")',
  },
  {
    fontFamily: 'Pangram Sans',
    fontStyle: 'normal',
    fontWeight: 100,
    fontDisplay: 'swap',
    src: 'url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-Bold.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-CompactExtralightReclined.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-CompactRegular.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-CompressedExtrabold.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-CompressedMediumReclined.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-CondensedThin.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-Light.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-Medium.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-NarrowExtralightReclined.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-NarrowSemibold.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-Semibold.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-SlimExtralight.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-SlimMediumReclined.d6aeafc5.woff2") format("woff2"), url("https://cdn.lafleche.dev/release/fonts/v1/Pangram+Sans.gen/PPPangramSans-Thin.d6aeafc5.woff2") format("woff2")',
  },
] as const;

for (const face of fontFaces) {
  const { fontFamily, ...fontFace } = face;
  globalFontFace(fontFamily, fontFace);
}

