import fs from 'node:fs/promises';
import path from 'node:path';

import fg from 'fast-glob';
import { execa } from 'execa';

const main = async () => {
  const passThrough = process.argv.slice(2);
  await execa(
    'node',
    ['scripts/generateSvgFromHeroText.mjs', ...passThrough],
    { stdio: 'inherit' },
  );
  const svgGlob = '/tmp/heroTextSvg/**/svgs/*.svg';
  await execa(
    'node',
    [
      'scripts/optimizeSvgs.mjs',
      svgGlob,
      '--write',
      '--shorten-ids',
      '--config=svgo.heroHeading.config.mts',
    ],
    { stdio: 'inherit' },
  );
  await execa(
    'prettier',
    ['--no-config', '--parser', 'html', svgGlob, '--write'],
    { stdio: 'inherit' },
  );

  const outputDir = path.resolve('src', 'assets', 'SVG', 'generated');
  await fs.mkdir(outputDir, { recursive: true });
  const svgPaths = await fg(svgGlob, {
    onlyFiles: true,
    dot: false,
    caseSensitiveMatch: false,
  });
  const toPascalCase = (value: string) =>
    value
      .split(/[^a-zA-Z0-9]+/g)
      .filter(Boolean)
      .map((part) => part[0].toUpperCase() + part.slice(1))
      .join('');
  type SvgEntry = {
    locale: string;
    pageName: string;
    name: string;
    outputName: string;
    componentName: string;
    componentId: string;
  };

  const entries: SvgEntry[] = await Promise.all(
    svgPaths.map(async (svgPath) => {
      const baseName = path.basename(svgPath);
      const match = baseName.match(/^([^.]+)\.svg$/i);
      const namePart = match ? match[1] : baseName;
      const parts = namePart.split('-');
      const locale = parts.shift() ?? 'unknown';
      const name = parts.join('-') || 'heroHeading';
      const pageName = path.basename(
        path.resolve(svgPath, '..', '..'),
      );
      const outputName = `${pageName}-${locale}-${name}.gen.svg`;
      const componentName = `${pageName}-${locale}-${name}.gen.tsx`;
      await fs.copyFile(svgPath, path.join(outputDir, outputName));
      const svgContent = await fs.readFile(svgPath, 'utf8');
      const normalizedSvg = svgContent.trim();
      const svgMatch = normalizedSvg.match(
        /^<svg([^>]*)>([\s\S]*)<\/svg>$/i,
      );
      if (!svgMatch) {
        throw new Error(
          `Unable to parse SVG root for ${svgPath}.`,
        );
      }
      const attributes = svgMatch[1].trim();
      const inner = svgMatch[2].trim();
      const innerIndented = inner
        .split('\n')
        .map((line) => (line ? `  ${line}` : line))
        .join('\n');
      const componentId =
        toPascalCase(
          `${pageName}-${locale}-${name}`,
        ) + 'Svg';
      const componentSource = `import type { SVGProps } from 'react';

const ${componentId} = (props: SVGProps<SVGSVGElement>) => (
  <svg${attributes ? ` ${attributes}` : ''} {...props}>
${innerIndented}
  </svg>
);

export default ${componentId};
`;
      await fs.writeFile(
        path.join(outputDir, componentName),
        componentSource,
        'utf8',
      );
      return {
        locale,
        pageName,
        name,
        outputName,
        componentName,
        componentId,
      };
    }),
  );

  const imports: string[] = [];
  const localeMap: Map<
    string,
    Map<string, Map<string, string>>
  > = new Map();

  for (const entry of entries) {
    const importId = entry.componentId;
    imports.push(
      `import ${importId} from './${entry.componentName}';`,
    );
    let pageMap = localeMap.get(entry.locale);
    if (!pageMap) {
      pageMap = new Map();
      localeMap.set(entry.locale, pageMap);
    }
    let nameMap = pageMap.get(entry.pageName);
    if (!nameMap) {
      nameMap = new Map();
      pageMap.set(entry.pageName, nameMap);
    }
    nameMap.set(entry.name, importId);
  }

  const localeEntries = [];
  for (const [locale, pages] of localeMap) {
    const pageEntries = [];
    for (const [pageName, names] of pages) {
      const nameEntries = [];
      for (const [name, importId] of names) {
        nameEntries.push(`${name}: ${importId}`);
      }
      pageEntries.push(
        `${pageName}: { ${nameEntries.join(', ')} }`,
      );
    }
    localeEntries.push(
      `${locale}: { ${pageEntries.join(', ')} }`,
    );
  }

  const generatedFile = `// Generated by scripts/buildHeroHeadingSvg.mts
import type { Locale } from '@/lib/locales/translations';
${imports.join('\n')}

export const generatedSvgs = {
  ${localeEntries.join(',\n  ')}
} as const;

export const getLocaleSvgs = (locale: Locale) => generatedSvgs[locale];
`;

  await fs.writeFile(
    path.join(outputDir, 'headingsAsSvgs.ts'),
    generatedFile,
    'utf8',
  );

  await execa('yarn', ['lint:cleanup'], { stdio: 'inherit' });
};

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
