// scripts/generateLocales.mjs
import fs from "fs";
import path from "path";
import prettier from "prettier";

const __dirname = path.resolve();

// Input: JSON files in src/locales
const localesDir = path.join(__dirname, "src", "locales");
// Output: generated TS file
const outputFile = path.join(__dirname, "src", "data", "locales.ts");

// Ensure locales dir exists
if (!fs.existsSync(localesDir)) {
  console.error("❌ src/locales directory not found.");
  process.exit(1);
}

// Read all JSON files
const files = fs.readdirSync(localesDir).filter((f) => f.endsWith(".json"));
const locales = {};
for (const file of files) {
  const locale = path.basename(file, ".json");
  const content = JSON.parse(
    fs.readFileSync(path.join(localesDir, file), "utf8"),
  );
  locales[locale] = content;
}

// Generate TypeScript content
const localesArray = Object.keys(locales)
  .map((l) => `"${l}"`)
  .join(" | ");

const generated = `
// This file is auto-generated by scripts/generateLocales.mjs
export const AVAILABLE_LOCALES = ${JSON.stringify(Object.keys(locales))} as const;
export const TRANSLATIONS = ${JSON.stringify(locales, null, 2)} as const;
export type Locale = ${localesArray};
`;

// Format with Prettier if available
let formatted = generated;
try {
  const options = await prettier.resolveConfig(outputFile);
  formatted = prettier.format(generated, { ...options, parser: "typescript" });
} catch {
  // prettier not available, skip
}

// Only write if content changed
let shouldWrite = true;
if (fs.existsSync(outputFile)) {
  const current = fs.readFileSync(outputFile, "utf8");
  if (current.trim() === formatted.trim()) {
    shouldWrite = false;
    console.log("✅ locales.ts is already up to date.");
  }
}

if (shouldWrite) {
  fs.writeFileSync(outputFile, formatted, "utf8");
  console.log("✨ locales.ts updated!");
}
