import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';
import {
	AVAILABLE_LOCALES,
	LOCALE_LOADERS,
} from '../src/lib/locales/translations/index.ts';

const markdownKeyPattern = /(?:^|[-_])content$/;
const extraMarkdownKeys = new Set(['hero-subtitle']);

function shouldConvert(key: string, value: unknown): value is string {
	if (typeof value !== 'string') return false;
	if (!value.trim()) return false;
	return markdownKeyPattern.test(key) || extraMarkdownKeys.has(key);
}

function wrapHtmlIfNeeded(key: string, rendered: string): string {
	if (rendered) return rendered;
	return `<p data-locale-key="${key}" />`;
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outputPath = path.resolve(
	__dirname,
	'../src/lib/locales/generated/html.gen.ts',
);

const makeBanner = () =>
	`// AUTO-GENERATED by scripts/generateCopyHtml.ts — DO NOT EDIT\n`;

async function main() {
	const htmlByLocale: Record<string, Record<string, string>> = {};

	// Ensure marked does not mangle email addresses or add header ids.
	marked.use({ mangle: false, headerIds: false });

	for (const locale of AVAILABLE_LOCALES) {
		const mod = await LOCALE_LOADERS[locale]();
		const messages = mod.default as Record<string, unknown>;
		const htmlMap: Record<string, string> = {};

		for (const [key, value] of Object.entries(messages)) {
			if (!shouldConvert(key, value)) continue;
			const rendered = wrapHtmlIfNeeded(
				key,
				marked.parse(value).trim(),
			);
			htmlMap[key] = rendered;
		}

		htmlByLocale[locale] = htmlMap;
	}

	const fileContents = `${makeBanner()}export const HTML_MESSAGES = ${JSON.stringify(htmlByLocale, null, 2)} as const;\n\nexport type HtmlMessages = typeof HTML_MESSAGES;\n`;

	await fs.mkdir(path.dirname(outputPath), { recursive: true });
	await fs.writeFile(outputPath, fileContents, 'utf8');

	console.log(`✅ Wrote ${outputPath}`);
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
