import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  generateGoogleFontUrls,
  type FontConfig,
} from '../src/lib/gfonts.ts';

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = path.resolve(path.dirname(__filename), '..');
const GOOGLE_FONTS_CONFIG = path.resolve(
  REPO_ROOT,
  'cdn',
  'media',
  'fonts',
  'localFontsSrc',
  'googleFonts.json',
);
const OUT_FILE = path.resolve(
  REPO_ROOT,
  'src',
  'data',
  'generated',
  'fonts',
  'googleFonts.gen.ts',
);

type FontCfgInput = FontConfig & { type?: string };
type FontsConfig = Record<string, FontCfgInput>;

async function main() {
  if (!fs.existsSync(GOOGLE_FONTS_CONFIG)) {
    throw new Error(
      `Missing ${GOOGLE_FONTS_CONFIG}. Add your Google font families there.`,
    );
  }
  const fontsConfig = JSON.parse(
    fs.readFileSync(GOOGLE_FONTS_CONFIG, 'utf8'),
  ) as FontsConfig;

  const resolvedMap: Record<string, FontConfig> = {};

  for (const [
    family,
    cfg,
  ] of Object.entries(fontsConfig)) {
    resolvedMap[family] = {
      weights: cfg.weights,
      ital: cfg.ital,
      subsets: cfg.subsets,
      axes: cfg.axes,
      rawAxis: cfg.rawAxis,
    };
  }

  const urls = generateGoogleFontUrls(resolvedMap, {
    display: 'swap',
    subsets: [
      'latin',
    ],
  });

  const linkDescriptors = urls.map((url) => ({
    preloadHref: url,
    stylesheetHref: url,
  }));

  const banner = `// AUTO-GENERATED by scripts/generateFontUrls.ts — DO NOT EDIT
export const GOOGLE_FONT_URLS = ${JSON.stringify(urls, null, 2)} as const;

export const GOOGLE_FONT_PRECONNECTS = [
  { href: "https://fonts.googleapis.com", crossOrigin: false },
  { href: "https://fonts.gstatic.com", crossOrigin: true }
] as const;

export const GOOGLE_FONT_LINK_DESCRIPTORS = ${JSON.stringify(
    linkDescriptors,
    null,
    2,
  )} as const;
`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, banner, 'utf8');

  const shouldVerify =
    String(process.env.VERIFY_FONT_URLS ?? '')
      .toLowerCase()
      .trim() === 'true';

  if (shouldVerify) {
    const uniqueUrls = Array.from(new Set(urls));

    await Promise.all(
      uniqueUrls.map(async (href) => {
        try {
          const response = await fetch(href, {
            method: 'HEAD',
          });
          if (!response.ok) {
            throw new Error(
              `HTTP ${response.status} ${response.statusText}`,
            );
          }
        } catch (error) {
          const message =
            error instanceof Error ? error.message : String(error);
          throw new Error(
            `Failed to verify Google Font URL "${href}": ${message}`,
          );
        }
      }),
    );
  }

  console.log(`✅ Wrote ${OUT_FILE}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
