// scripts/generateFontUrls.ts
/* eslint-disable no-console */
import fs from 'node:fs';
import path from 'node:path';

// Use relative imports so we don't depend on tsconfig path aliases here.
// If your TS config requires it, enable:
//   "moduleResolution": "Bundler",
//   "allowImportingTsExtensions": true
import { generateGoogleFontUrls } from '../src/lib/gfonts.ts';

// ---- Paths (match locales output folder) ----
const LOCALES_JSON = path.resolve(
	'src',
	'data',
	'generated',
	'locales.gen.json',
);
const FONTS_CONFIG = path.resolve('src', 'data', 'fonts.config.json');
const OUT_FILE = path.resolve('src', 'data', 'generated', 'googleFonts.gen.ts');

// ---- Types (lightweight runtime shapes) ----
type FontCfgInput = {
	texts?: string[];
	keys?: string[];
	weights: string | string[];
	ital?: boolean;
	subsets?: string[];
};
type FontsConfig = Record<string, FontCfgInput>;

type PerLocaleMinSets = {
	perLocale: Record<string, Record<string, string>>; // [locale][family] -> unique chars ("" if none)
};

function main() {
	// --- Load generated locales JSON (must exist from `yarn locales`) ---
	if (!fs.existsSync(LOCALES_JSON)) {
		throw new Error(`Missing ${LOCALES_JSON}. Run "yarn locales" first.`);
	}
	const localesPayload = JSON.parse(fs.readFileSync(LOCALES_JSON, 'utf8')) as {
		AVAILABLE_LOCALES: string[];
		FONT_MIN_SETS: PerLocaleMinSets;
	};
	const { AVAILABLE_LOCALES, FONT_MIN_SETS } = localesPayload;
	if (!FONT_MIN_SETS || !FONT_MIN_SETS.perLocale) {
		throw new Error(
			`Invalid locales payload: FONT_MIN_SETS.perLocale missing in ${LOCALES_JSON}`,
		);
	}

	// --- Load fonts config (weights/ital/subsets) ---
	if (!fs.existsSync(FONTS_CONFIG)) {
		throw new Error(`Missing ${FONTS_CONFIG}. Add your font families there.`);
	}
	const fontsConfig = JSON.parse(
		fs.readFileSync(FONTS_CONFIG, 'utf8'),
	) as FontsConfig;

	// --- Build per-locale URLs map ---
	const urlsByLocale: Record<string, string[]> = {};

	for (const locale of AVAILABLE_LOCALES) {
		const perFontChars = FONT_MIN_SETS.perLocale[locale] || {};
		const resolvedMap: Record<
			string,
			{
				texts?: string[];
				weights: string | string[];
				ital?: boolean;
				subsets?: string[];
			}
		> = {};

		for (const [family, cfg] of Object.entries(fontsConfig)) {
			const charset = perFontChars[family] || '';
			resolvedMap[family] = {
				// If charset is non-empty, pass it as a single-item texts array so we get &text=...
				texts: charset ? [charset] : undefined,
				weights: cfg.weights,
				ital: cfg.ital,
				subsets: cfg.subsets,
			};
		}

		urlsByLocale[locale] = generateGoogleFontUrls(resolvedMap, {
			display: 'swap',
			subsets: ['latin'], // per-font can override via cfg.subsets
			stripWhitespaceFromText: false, // already collapsed; keep as-is
		});
	}

	// --- Emit TS module with per-locale URL arrays ---
	const banner = `// AUTO-GENERATED by scripts/generateFontUrls.ts — DO NOT EDIT
export const GOOGLE_FONT_URLS_BY_LOCALE = ${JSON.stringify(urlsByLocale, null, 2)} as const;
`;

	fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
	fs.writeFileSync(OUT_FILE, banner, 'utf8');
	console.log(
		`✅ Wrote ${OUT_FILE} for locales: ${AVAILABLE_LOCALES.join(', ')}`,
	);
}

main();
