import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';
import { AVAILABLE_LOCALES } from '../src/lib/locales/translations/index.ts';
import { loadMessages } from '../src/lib/locales/locale.ts';

const markdownKeyPattern = /(?:^|[-_])content$/;
function shouldConvert(key: string, value: unknown): value is string {
  if (typeof value !== 'string') return false;
  if (!value.trim()) return false;
  return markdownKeyPattern.test(key);
}

function wrapHtmlIfNeeded(key: string, rendered: string): string {
  if (rendered) return rendered;
  return `<p data-locale-key="${key}" />`;
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outputPath = path.resolve(
  __dirname,
  '../src/lib/locales/generated/html.gen.ts',
);

const makeBanner = () =>
  `// AUTO-GENERATED by scripts/generateCopyHtml.ts — DO NOT EDIT\n`;

async function main() {
  const htmlByLocale: Record<string, Record<string, string>> = {};

  for (const locale of AVAILABLE_LOCALES) {
    const messages = await loadMessages(locale);
    const htmlMap: Record<string, string> = {};

    for (const [
      key,
      value,
    ] of Object.entries(messages)) {
      if (!shouldConvert(key, value)) continue;
      const renderedMarkdown = marked.parse(value);
      if (typeof renderedMarkdown !== 'string') {
        throw new Error(`Expected markdown render for "${key}" to be a string.`);
      }
      const rendered = wrapHtmlIfNeeded(
        key,
        renderedMarkdown.trim(),
      );
      htmlMap[key] = rendered;
    }

    htmlByLocale[locale] = htmlMap;
  }

  const fileContents = `${makeBanner()}export const HTML_MESSAGES = ${JSON.stringify(htmlByLocale, null, 2)} as const;\n\nexport type HtmlMessages = typeof HTML_MESSAGES;\n`;

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, fileContents, 'utf8');

  console.log(`✅ Wrote ${outputPath}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
