import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
	AVAILABLE_LOCALES,
	type Locale,
} from '../src/lib/locales/translations/index.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const markdownDir = path.resolve(
	__dirname,
	'../src/lib/locales/translations/markdown',
);
const outputPath = path.resolve(
	__dirname,
	'../src/lib/locales/generated/markdown.gen.ts',
);

const BANNER =
	'// AUTO-GENERATED by scripts/generateLocaleMarkdown.ts — DO NOT EDIT\n';
const MARKDOWN_FILE_PATTERN =
	/^(?<locale>[a-z]{2})-(?<section>[a-z0-9-]+)-(?<key>[a-z0-9_]+)\.md$/i;

type MarkdownMessages = Partial<
	Record<Locale, Record<string, string>>
>;

const validateLocale = (locale: string): locale is Locale =>
	(AVAILABLE_LOCALES as readonly string[]).includes(locale);

async function readMarkdownFiles(): Promise<{
	messages: MarkdownMessages;
	keys: Set<string>;
}> {
	const messages: MarkdownMessages = {};
	const keys = new Set<string>();

	await fs.mkdir(markdownDir, { recursive: true });
	const files = await fs.readdir(markdownDir);

	await Promise.all(
		files
			.filter((file) => file.endsWith('.md'))
			.map(async (file) => {
				const match = file.match(MARKDOWN_FILE_PATTERN);
				if (!match?.groups) {
					throw new Error(
						`[locales] Markdown file "${file}" does not match expected pattern "<locale>-<section>-<key>.md".`,
					);
				}

				const { key, locale } = match.groups;
				if (!validateLocale(locale)) {
					throw new Error(
						`[locales] Markdown file "${file}" references unknown locale "${locale}".`,
					);
				}

				const messageKey = key.replace(/_/g, '-');

				const content = await fs.readFile(
					path.join(markdownDir, file),
					'utf8',
				);

				if (!messages[locale as Locale]) {
					messages[locale as Locale] = {};
				}

				messages[locale as Locale]![messageKey] = content;
				keys.add(messageKey);
			}),
	);

	return { messages, keys };
}

function buildFileContents(
	messages: MarkdownMessages,
	keys: Set<string>,
): string {
	const sortedKeys = Array.from(keys).sort();
	const localeUnion = AVAILABLE_LOCALES.map((locale) => `'${locale}'`).join(
		' | ',
	);

	const completeMessages: Record<string, Record<string, string>> = {};
	for (const locale of AVAILABLE_LOCALES) {
		const localeMessages = messages[locale] ?? {};
		const ordered: Record<string, string> = {};
		for (const key of sortedKeys) {
			if (localeMessages[key] !== undefined) {
				ordered[key] = localeMessages[key];
			}
		}
		completeMessages[locale] = ordered;
	}

	const serializedKeys = JSON.stringify(sortedKeys, null, 2);
	const serializedMessages = serializeMarkdownMessages(
		completeMessages,
	);

	return `${BANNER}import type { MarkdownContent } from '../markdownTypes';\n\nexport const MARKDOWN_MESSAGE_KEYS = ${serializedKeys} as const;\n\nexport type MarkdownMessageKey = (typeof MARKDOWN_MESSAGE_KEYS)[number];\n\ntype LocaleKey = ${localeUnion};\n\nexport const MARKDOWN_MESSAGES = ${serializedMessages} as const satisfies Record<LocaleKey, Record<MarkdownMessageKey, MarkdownContent>>;\n`;
}

function serializeMarkdownMessages(
	messages: Record<string, Record<string, string>>,
) {
	const lines: string[] = ['{'];

	for (const locale of AVAILABLE_LOCALES) {
		const localeMessages = messages[locale] ?? {};
		const entries = Object.entries(localeMessages);

		if (entries.length === 0) {
			lines.push(`  ${JSON.stringify(locale)}: {},`);
			continue;
		}

		lines.push(`  ${JSON.stringify(locale)}: {`);
		for (const [key, value] of entries) {
			const serializedValue = JSON.stringify(value);
			lines.push(
				`    ${JSON.stringify(key)}: ${serializedValue} as MarkdownContent,`,
			);
		}
		lines.push('  },');
	}

	lines.push('}');
	return lines.join('\n');
}

async function main() {
	const { messages, keys } = await readMarkdownFiles();
	const fileContents = buildFileContents(messages, keys);

	await fs.mkdir(path.dirname(outputPath), { recursive: true });
	await fs.writeFile(outputPath, fileContents, 'utf8');

	console.log(`✅ Wrote ${outputPath}`);
}

main().catch((error) => {
	console.error(error);
	process.exit(1);
});
