import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { DEFAULT_LOCALE } from '../src/lib/locales/locale.ts';
import { AVAILABLE_LOCALES } from '../src/lib/locales/translations/index.ts';
import {
  faviconAssetPlan,
  faviconThemeColors,
} from '../src/tokens/favicon.tokens';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const MANIFEST_TS_PATH = path.resolve(
  __dirname,
  '../src/data/generated/favicons.manifest.gen.ts',
);

const PUBLIC_ROOT = '/favicons';

async function main() {
  try {
    const existing = await fs.readFile(MANIFEST_TS_PATH, 'utf8');
    if (existing.includes('scripts/generateFavicons.ts')) {
      console.log(
        `ℹ️  Favicons manifest already generated by full pipeline, skipping mock generation.`,
      );
      return;
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT')
      throw error;
  }

  const locales = [
    ...AVAILABLE_LOCALES,
  ];
  const defaultLocale = DEFAULT_LOCALE;

  const svg = {
    src: `${PUBLIC_ROOT}/favicon.svg`,
    fileName: 'favicon.svg',
    hash: 'mock',
  };

  const ico = {
    src: `${PUBLIC_ROOT}/favicon.ico`,
    fileName: 'favicon.ico',
    hash: 'mock',
  };

  const pngVariants = [
    {
      size: 192,
      src: `${PUBLIC_ROOT}/icon-192x192.png`,
      fileName: 'icon-192x192.png',
      hash: 'mock',
    },
  ];

  const androidIcons = [
    {
      size: 192,
      src: `${PUBLIC_ROOT}/android-chrome-192x192.png`,
      fileName: 'android-chrome-192x192.png',
      hash: 'mock',
      sizes: '192x192',
    },
  ];

  const appleTouch = {
    src: `${PUBLIC_ROOT}/apple-touch-icon.png`,
    fileName: 'apple-touch-icon.png',
    hash: 'mock',
    size: 180,
  };

  const maskIcon = {
    src: `${PUBLIC_ROOT}/safari-pinned-tab.svg`,
    fileName: 'safari-pinned-tab.svg',
    hash: 'mock',
    color: faviconThemeColors.maskIcon,
  };

  const maskableIcon = {
    src: `${PUBLIC_ROOT}/maskable-icon.png`,
    fileName: 'maskable-icon.png',
    hash: 'mock',
    size: faviconAssetPlan.maskableSize,
  };

  const msTile = {
    src: `${PUBLIC_ROOT}/mstile-150x150.png`,
    fileName: 'mstile-150x150.png',
    hash: 'mock',
    size: 150,
    color: faviconThemeColors.msTile,
  };

  const browserConfig = {
    src: `${PUBLIC_ROOT}/browserconfig.xml`,
    fileName: 'browserconfig.xml',
    hash: 'mock',
  };

  const metaTags = {
    themeColorLight: faviconThemeColors.light,
    themeColorDark: faviconThemeColors.dark,
    msTileColor: faviconThemeColors.msTile,
    msApplicationConfig: browserConfig.src,
  };

  const manifestMetaByLocale = Object.fromEntries(
    locales.map((locale) => [
      locale,
      {
        locale,
        name: 'Mock App',
        shortName: 'Mock App',
        description: 'Mock favicon manifest for fast pipelines.',
        categories: [
          'productivity',
        ],
        lang: locale,
      },
    ]),
  );

  const faviconMetaByLocale = Object.fromEntries(
    locales.map((locale) => [
      locale,
      {
        description: 'Mock description',
        keywords: 'mock, favicons',
        author: 'Mock Author',
      },
    ]),
  );

  const webManifestExportMap = Object.fromEntries(
    locales.map((locale) => [
      locale,
      {
        src: `${PUBLIC_ROOT}/site-${locale}.webmanifest`,
        fileName: `site-${locale}.webmanifest`,
        hash: 'mock',
      },
    ]),
  );

  const defaultWebManifest = {
    locale: defaultLocale,
    src: `${PUBLIC_ROOT}/site-${defaultLocale}.webmanifest`,
    fileName: `site-${defaultLocale}.webmanifest`,
    hash: 'mock',
  };

  const appConfig = {
    startUrl: '/',
    scope: '/',
    display: 'standalone',
    orientation: 'portrait',
  };

  const themeColors = {
    light: faviconThemeColors.light,
    dark: faviconThemeColors.dark,
    background: faviconThemeColors.background,
    maskIcon: faviconThemeColors.maskIcon,
    msTile: faviconThemeColors.msTile,
  };

  const linkDescriptorsByLocale = Object.fromEntries(
    locales.map((locale) => [
      locale,
      {
        main: [
          {
            rel: 'icon' as const,
            type: 'image/svg+xml',
            sizes: 'any',
            href: svg.src,
          },
          {
            rel: 'icon' as const,
            type: 'image/png',
            sizes: '192x192',
            href: pngVariants[0].src,
          },
          {
            rel: 'apple-touch-icon' as const,
            sizes: `${appleTouch.size}x${appleTouch.size}`,
            href: appleTouch.src,
          },
          {
            rel: 'mask-icon' as const,
            color: faviconThemeColors.maskIcon,
            href: maskIcon.src,
          },
          {
            rel: 'manifest' as const,
            href: webManifestExportMap[locale].src,
          },
        ],
      },
    ]),
  );

  const manifestTs = `// AUTO-GENERATED by scripts/generateMockFavicons.ts — DO NOT EDIT
export const FAVICON_SVG = ${JSON.stringify(svg, null, 2)} as const;

export const FAVICON_ICO = ${JSON.stringify(ico, null, 2)} as const;

export const FAVICON_PNG_VARIANTS = ${JSON.stringify(
    pngVariants,
    null,
    2,
  )} as const;

export const FAVICON_APPLE_TOUCH_ICON = ${JSON.stringify(
    appleTouch,
    null,
    2,
  )} as const;

export const FAVICON_ANDROID_ICONS = ${JSON.stringify(
    androidIcons,
    null,
    2,
  )} as const;

export const FAVICON_MASK_ICON = ${JSON.stringify(
    maskIcon,
    null,
    2,
  )} as const;

export const FAVICON_MASKABLE_ICON = ${JSON.stringify(
    maskableIcon,
    null,
    2,
  )} as const;

export const FAVICON_MS_TILE = ${JSON.stringify(
    msTile,
    null,
    2,
  )} as const;

export const FAVICON_BROWSERCONFIG = ${JSON.stringify(
    browserConfig,
    null,
    2,
  )} as const;

export const FAVICON_DEV_MASK_SVG_PATH = ${JSON.stringify(
    null,
    null,
    2,
  )};

export const FAVICON_DEV_TILE_FOREGROUND_SVG_PATH = ${JSON.stringify(
    null,
    null,
    2,
  )};

export const FAVICON_MANIFEST_META_BY_LOCALE = ${JSON.stringify(
    manifestMetaByLocale,
    null,
    2,
  )} as const;

export const FAVICON_META_BUNDLES_BY_LOCALE = ${JSON.stringify(
    faviconMetaByLocale,
    null,
    2,
  )} as const;

export const FAVICON_WEB_MANIFESTS = ${JSON.stringify(
    webManifestExportMap,
    null,
    2,
  )} as const;

export const FAVICON_DEFAULT_WEB_MANIFEST = ${JSON.stringify(
    defaultWebManifest,
    null,
    2,
  )} as const;

export const FAVICON_APP_CONFIG = ${JSON.stringify(
    appConfig,
    null,
    2,
  )} as const;

export const FAVICON_THEME_COLORS = ${JSON.stringify(
    themeColors,
    null,
    2,
  )} as const;

export const FAVICON_META_TAGS = ${JSON.stringify(
    metaTags,
    null,
    2,
  )} as const;

export const FAVICON_LINK_DESCRIPTORS_BY_LOCALE = ${JSON.stringify(
    linkDescriptorsByLocale,
    null,
    2,
  )} as const;
`;

  await fs.mkdir(path.dirname(MANIFEST_TS_PATH), { recursive: true });
  await fs.writeFile(MANIFEST_TS_PATH, manifestTs, 'utf8');

  console.log(
    `✅ Wrote mock favicons manifest → ${MANIFEST_TS_PATH}`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
